AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  A simple Hello World Serverless project

Resources:
  SomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Environment:
        Variables:
          ENV_VAR:
      Events:
        MyFunction:
          Type: Api
          Properties:
            Path: /some-path/{pathParam}
            Method: any

